spring:
  profiles:
    active: core
---
server:
  port: 8080
spring:
  config:
    activate:
      on-profile:
  datasource:
    url: 'jdbc:postgresql://localhost:5433/people'
    driver-class-name: 'org.postgresql.Driver'
    username: people
    password: people
  flyway:
    locations: 'classpath:/db/migration'
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    hibernate:
      naming:
        physical-strategy: 'org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy'
      ddl-auto: update
    show-sql: true
  task:
    execution:
      pool:
        core-size: 8
        max-size: 8
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
